---
title: "eBird Data"
author: "Joshua Pearcy"
date: "6/25/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The code below will produce a data frame for the ABA code 4 and 5 birds from 2008-2017. 

```{r}
# set the library so we can use the auk package
library(auk)
# set the path to the EBD data 
auk_set_ebd_path("C:/Users/joshp/OneDrive/Documents/eBird",overwrite = TRUE)
# import the EBD txt file into R
fin = "C:/Users/joshp/OneDrive/Documents//eBird/ebd_US_relMay-2021.txt"
# creates an output file for the filtered data
fout = "ebd_filtereddata.txt"
# creates a temporary file 
tempdata = "ebd_tempfile.txt"
# tells R that your working with EBD data
ebdata = auk_ebd(fin)
# tells R to filter out all the observations from 2008-2017
ebdfilter = auk_date(ebdata,date=c("2008-01-31","2017-12-31"))
# tells R to filter out all the ABA code 4 and 5 bird species
ebdfiltes1 = auk_species(ebdfilter,c("Anser anser","Anser brachyrhynchus","Branta leucopsis","Tadorna tadorna","Sibirionetta formosa","Spatula querquedula","Mareca falcata","Anas zonorhyncha","Anas bahamensis","Melanitta stejnegeri","Melanitta nigra","Columba palumbus","Patagioenas squamosa","Streptopelia orientalis","Streptopelia turtur","Geotrygon montana","Geotrygon chrysia","Zenaida aurita","Cuculus optatus","Caprimulgus jotaka","Streptoprocne zonaris","Hirundapus caudacutus","Apus apus","Apus pacificus","Tachornis phoenicobia","Anthracothorax prevostii",
"Lampornis amethystinus","Nesophlox evelynae","Amazilia rutila","Pardirallus maculatus","Aramides axillaris","Crex crex","Gallinula chloropus","Fulica atra","Heliornis fulica","Grus grus","Grus monacha","Burhinus bistriatus","Himantopus himantopus","Haematopus ostralegus","Vanellus vanellus","Pluvialis apricaria","Charadrius morinellus","Charadrius dubius","Charadrius leschenaultii","Charadrius collaris","Jacana spinosa","Numenius minutus","Numenius madagascariensis","Numenius tenuirostris",
"Numenius arquata","Calidris tenuirostris","Calidris falcinellus","Calidris minuta","Lymnocryptes minimus","Scolopax rusticola","Gallinago solitaria","Gallinago stenura","Tringa ochropus","Tringa erythropus","Tringa totanus","Tringa stagnatilis","Glareola maldivarum","Creagrus furcatus","Chroicocephalus cirrocephalus","Ichthyaetus ichthyaetus","Larus belcheri","Larus crassirostris","Larus michahellis","Larus dominicanus","Sternula albifrons","Phaetusa simplex","Chlidonias leucopterus","Chlidonias hybrida","Thalasseus bergii","Thalassarche chlororhynchos","Thalassarche cauta",
"Thalassarche eremita","Thalassarche salvini","Thalassarche melanophris","Phoebetria palpebrata","Diomedea exulans","Fregetta tropica","Hydrobates pelagicus","Macronectes halli","Pterodroma gouldi","Pterodroma solandri","Pterodroma neglecta","Pterodroma heraldica","Pterodroma madeira","Pterodroma longirostris",
"Pseudobulweria rostrata","Bulweria fallax","Procellaria aequinoctialis",
"Procellaria parkinsoni","Calonectris leucomelas","Calonectris edwardsii","Puffinus bryani","Puffinus baroli","Jabiru mycteria","Fregata ariel","Sula granti","Sula nebouxii","Ixobrychus sinensis","Tigrisoma mexicanum","Ardea cinerea","Ardea intermedia","Egretta eulophotes","Egretta garzetta","Egretta gularis","Ardeola bacchus","Eudocimus ruber","Harpagus bidentatus","Accipiter soloensis","Milvus migrans","Haliaeetus albicilla","Haliaeetus pelagicus","Geranospiza caerulescens","Buteogallus urubitinga","Rupornis magnirostris","Buteo rufinus","Otus sunia","Ciccaba virgata","Asio stygius","Ninox japonica","Euptilotis neoxenus","Upupa epops","Chloroceryle amazona","Jynx torquilla","Dendrocopos major","Micrastur semitorquatus","Falco tinnunculus","Falco vespertinus","Falco subbuteo","Rhynchopsitta pachyrhyncha","Tityra semifasciata","Pachyramphus major","Myiopagis viridicata","Elaenia albiceps","Myiarchus nuttingi","Myiozetetes similis","Legatus leucophaius","Empidonomus varius","Empidonomus aurantioatrocristatus","Tyrannus caudifasciatus","Mitrephanes phaeocercus","Contopus caribaeus","Empidonax affinis","Lanius cristatus","Lanius collurio","Vireo crassirostris","Vireo gundlachii","Vireo magister","Psilorhinus morio","Corvus monedula","Corvus imparatus","Tachycineta cyaneoviridis","Tachycineta albilinea","Progne tapera","Progne elegans","Progne chalybea","Progne cryptoleuca","Delichon urbicum","Thryophilus sinaloa","Phylloscopus trochilus","Phylloscopus collybita","Phylloscopus sibilatrix","Phylloscopus fuscatus","Phylloscopus proregulus","Phylloscopus inornatus","Phylloscopus examinandus","Sylvia curruca","Acrocephalus schoenobaenus","Acrocephalus dumetorum","Locustella lanceolata","Locustella fluviatilis","Muscicapa griseisticta","Muscicapa dauurica","Muscicapa striata","Muscicapa sibirica","Erithacus rubecula","Larvivora cyane","Larvivora sibilans","Tarsiger cyanurus","Ficedula narcissina","Ficedula mugimaki","Ficedula albicilla","Phoenicurus phoenicurus","Saxicola torquatus","Oenanthe pleschanka","Myadestes occidentalis","Catharus aurantiirostris","Catharus mexicanus","Turdus viscivorus","Turdus merula","Turdus eunomus","Turdus pilaris","Turdus iliacus","Turdus philomelos","Turdus assimilis","Turdus plumbeus","Ridgwayia pinicola","Melanotis caerulescens","Mimus gundlachii","Ptiliogonys cinereus","Prunella montanella","Lonchura malacca","Motacilla citreola","Motacilla cinerea","Anthus trivialis","Anthus gustavi","Fringilla coelebs","Coccothraustes coccothraustes","Carpodacus erythrinus","Carpodacus roseus","Pyrrhula pyrrhula","Leucosticte arctoa","Chloris sinica","Spinus spinus","Emberiza leucocephalos","Emberiza chrysophrys","Emberiza pusilla","Emberiza elegans","Emberiza aureola","Emberiza variabilis","Emberiza pallasi","Emberiza schoeniclus","Spizella wortheni","Icterus wagleri","Icterus pustulatus","Icterus abeillei","Agelaius humeralis","Oreothlypis superciliosa","Geothlypis poliocephala","Basileuterus culicivorus","Myioborus miniatus","Rhodothraupis celaeno","Pheucticus chrysopeplus","Cyanocompsa parellina","Cyanerpes cyaneus","Coereba flaveola","Melanospiza bicolor"))
# processes the filter request above
ebdfiltered = auk_filter(ebdfiltes1,file=fout,awk_file=tempdata,execute = TRUE,overwrite = TRUE)
# creates a data frame for the filtered EBD data
ebdf = read_ebd(ebdfiltered)
```

The code below will produce a data frame for the ABA code 3, 4 and 5 birds from 2008-2017. 

```{r}
# set the library so we can use the auk package
library(auk)
# set the path to the EBD data 
auk_set_ebd_path("C:/Users/joshp/OneDrive/Documents/eBird",overwrite = TRUE)
# import the EBD txt file into R
fin = "C:/Users/joshp/OneDrive/Documents//eBird/ebd_US_relMay-2021.txt"
# creates an output file for the filtered data
fout1 = "ebd_filtereddata1.txt"
# creates a temporary file 
tempdata1 = "ebd_tempfile1.txt"
# tells R that your working with EBD data
ebdata = auk_ebd(fin)
# tells R to filter out all the observations from 2008-2017
ebdfilter = auk_date(ebdata,date=c("2008-01-31","2017-12-31"))
# tells R to filter out all the ABA code 3, 4 and 5 bird species
ebdfiltes2 = auk_species(ebdfilter,c("Anser fabalis","Anser serrirostris","Cygnus cygnus","Aythya ferina","Aythya fuligula","Mergellus albellus","Nomonyx dominicus","Phoenicopterus ruber","Pterocles exustus","Columbina talpacoti","Crotophaga ani","Cuculus canorus","Antrostomus ridgwayi","Aerodramus bartschi","Colibri thalassinus","Charadrius hiaticula","Charadrius mongolus","Limosa limosa","Calidris pugnax","Calidris acuminata","Calidris ferruginea","Calidris temminckii","Calidris subminuta","Calidris ruficollis","Gallinago gallinago","Xenus cinereus","Actitis hypoleucos","Tringa brevipes","Tringa nebularia","Stercorarius skua","Brachyramphus perdix","Synthliboramphus hypoleucus","Synthliboramphus craveri","Pagophila eburnea","Rhodostethia rosea","Larus livens","Larus schistisagus","Anous ceruleus","Phaethon aethereus","Phaethon rubricauda","Phoebastria albatrus","Pelagodroma marina","Pterodroma arminjoniana","Pterodroma ultima","Pterodroma cahow","Pterodroma externa","Pterodroma sandwichensis","Pterodroma cervicalis","Pterodroma hypoleuca","Pterodroma nigripennis","Pterodroma feae","Pterodroma cookii","Bulweria bulwerii","Ardenna carneipes","Puffinus nativitatis","Puffinus newelli","Fregata minor","Sula dactylatra","Chondrohierax uncinatus","Glaucidium brasilianum","Falco femoralis","Pachyramphus aglaiae","Myiarchus sagrae","Tyrannus savana","Vireo flavoviridis","Chasiempis ibidis","Poecile cinctus","Polioptila nigriceps","Acrocephalus familiaris","Calliope calliope","Myadestes palmeri","Turdus obscurus","Turdus rufopalliatus","Motacilla alba","Anthus hodgsoni","Anthus cervinus","Fringilla montifringilla","Oreomystis bairdi","Loxioides bailleui","Telespiza cantans","Telespiza ultima","Palmeria dolei","Pseudonestor xanthophrys","Hemignathus wilsoni","Loxops mana","Loxops caeruleirostris","Loxops coccineus","Serinus canaria","Plectrophenax hyperboreus","Emberiza rustica","Amphispiza quinquestriata","Spindalis zena","Molothrus bonariensis","Setophaga pitiayumi","Basileuterus rufifrons","Piranga bidentata","Tiaris olivaceus","Sporophila morelleti","Anser anser","Anser brachyrhynchus","Branta leucopsis","Tadorna tadorna","Sibirionetta formosa","Spatula querquedula","Mareca falcata","Anas zonorhyncha","Anas bahamensis","Melanitta stejnegeri","Melanitta nigra","Columba palumbus","Patagioenas squamosa","Streptopelia orientalis","Streptopelia turtur","Geotrygon montana","Geotrygon chrysia","Zenaida aurita","Cuculus optatus","Caprimulgus jotaka","Streptoprocne zonaris","Hirundapus caudacutus","Apus apus","Apus pacificus","Tachornis phoenicobia","Anthracothorax prevostii",
"Lampornis amethystinus","Nesophlox evelynae","Amazilia rutila","Pardirallus maculatus","Aramides axillaris","Crex crex","Gallinula chloropus","Fulica atra","Heliornis fulica","Grus grus","Grus monacha","Burhinus bistriatus","Himantopus himantopus","Haematopus ostralegus","Vanellus vanellus","Pluvialis apricaria","Charadrius morinellus","Charadrius dubius","Charadrius leschenaultii","Charadrius collaris","Jacana spinosa","Numenius minutus","Numenius madagascariensis","Numenius tenuirostris",
"Numenius arquata","Calidris tenuirostris","Calidris falcinellus","Calidris minuta","Lymnocryptes minimus","Scolopax rusticola","Gallinago solitaria","Gallinago stenura","Tringa ochropus","Tringa erythropus","Tringa totanus","Tringa stagnatilis","Glareola maldivarum","Creagrus furcatus","Chroicocephalus cirrocephalus","Ichthyaetus ichthyaetus","Larus belcheri","Larus crassirostris","Larus michahellis","Larus dominicanus","Sternula albifrons","Phaetusa simplex","Chlidonias leucopterus","Chlidonias hybrida","Thalasseus bergii","Thalassarche chlororhynchos","Thalassarche cauta",
"Thalassarche eremita","Thalassarche salvini","Thalassarche melanophris","Phoebetria palpebrata","Diomedea exulans","Fregetta tropica","Hydrobates pelagicus","Macronectes halli","Pterodroma gouldi","Pterodroma solandri","Pterodroma neglecta","Pterodroma heraldica","Pterodroma madeira","Pterodroma longirostris",
"Pseudobulweria rostrata","Bulweria fallax","Procellaria aequinoctialis",
"Procellaria parkinsoni","Calonectris leucomelas","Calonectris edwardsii","Puffinus bryani","Puffinus baroli","Jabiru mycteria","Fregata ariel","Sula granti","Sula nebouxii","Ixobrychus sinensis","Tigrisoma mexicanum","Ardea cinerea","Ardea intermedia","Egretta eulophotes","Egretta garzetta","Egretta gularis","Ardeola bacchus","Eudocimus ruber","Harpagus bidentatus","Accipiter soloensis","Milvus migrans","Haliaeetus albicilla","Haliaeetus pelagicus","Geranospiza caerulescens","Buteogallus urubitinga","Rupornis magnirostris","Buteo rufinus","Otus sunia","Ciccaba virgata","Asio stygius","Ninox japonica","Euptilotis neoxenus","Upupa epops","Chloroceryle amazona","Jynx torquilla","Dendrocopos major","Micrastur semitorquatus","Falco tinnunculus","Falco vespertinus","Falco subbuteo","Rhynchopsitta pachyrhyncha","Tityra semifasciata","Pachyramphus major","Myiopagis viridicata","Elaenia albiceps","Myiarchus nuttingi","Myiozetetes similis","Legatus leucophaius","Empidonomus varius","Empidonomus aurantioatrocristatus","Tyrannus caudifasciatus","Mitrephanes phaeocercus","Contopus caribaeus","Empidonax affinis","Lanius cristatus","Lanius collurio","Vireo crassirostris","Vireo gundlachii","Vireo magister","Psilorhinus morio","Corvus monedula","Corvus imparatus","Tachycineta cyaneoviridis","Tachycineta albilinea","Progne tapera","Progne elegans","Progne chalybea","Progne cryptoleuca","Delichon urbicum","Thryophilus sinaloa","Phylloscopus trochilus","Phylloscopus collybita","Phylloscopus sibilatrix","Phylloscopus fuscatus","Phylloscopus proregulus","Phylloscopus inornatus","Phylloscopus examinandus","Sylvia curruca","Acrocephalus schoenobaenus","Acrocephalus dumetorum","Locustella lanceolata","Locustella fluviatilis","Muscicapa griseisticta","Muscicapa dauurica","Muscicapa striata","Muscicapa sibirica","Erithacus rubecula","Larvivora cyane","Larvivora sibilans","Tarsiger cyanurus","Ficedula narcissina","Ficedula mugimaki","Ficedula albicilla","Phoenicurus phoenicurus","Saxicola torquatus","Oenanthe pleschanka","Myadestes occidentalis","Catharus aurantiirostris","Catharus mexicanus","Turdus viscivorus","Turdus merula","Turdus eunomus","Turdus pilaris","Turdus iliacus","Turdus philomelos","Turdus assimilis","Turdus plumbeus","Ridgwayia pinicola","Melanotis caerulescens","Mimus gundlachii","Ptiliogonys cinereus","Prunella montanella","Lonchura malacca","Motacilla citreola","Motacilla cinerea","Anthus trivialis","Anthus gustavi","Fringilla coelebs","Coccothraustes coccothraustes","Carpodacus erythrinus","Carpodacus roseus","Pyrrhula pyrrhula","Leucosticte arctoa","Chloris sinica","Spinus spinus","Emberiza leucocephalos","Emberiza chrysophrys","Emberiza pusilla","Emberiza elegans","Emberiza aureola","Emberiza variabilis","Emberiza pallasi","Emberiza schoeniclus","Spizella wortheni","Icterus wagleri","Icterus pustulatus","Icterus abeillei","Agelaius humeralis","Oreothlypis superciliosa","Geothlypis poliocephala","Basileuterus culicivorus","Myioborus miniatus","Rhodothraupis celaeno","Pheucticus chrysopeplus","Cyanocompsa parellina","Cyanerpes cyaneus","Coereba flaveola","Melanospiza bicolor"))
# processes the filter request above
ebdfiltered1 = auk_filter(ebdfiltes2,file=fout1,awk_file=tempdata1,execute = TRUE,overwrite = TRUE)
# creates a data frame for the filtered EBD data
ebdf1 = read_ebd(ebdfiltered1)
```

